#!/usr/bin/python3
import sys, random
from math import gcd

def find_factor(num):
    if num <= 3:
        return num
    elif num % 2 == 0:
        return 2
    elif num % 3 == 0:
        return 3
    ret = num
    while ret == num:
        x = y = 2
        c = random.randint(2, num - 1)
        f = lambda x: (x ** 2 + c) % num
        d = 1
        while d == 1:
            x = f(x)
            y = f(f(y))
            d = gcd(abs(x - y), num)
            if d != num:
                return d
    '''
    while ret == num:
        x = y = 2
        c = random.randint(2, num - 1)
        f = lambda x: x ** 2 + c
        ret = 1
        while ret == 1:
            x = f(x) % num
            y = f(f(y)) % num
            ret = gcd(abs(x - y) % num, num) '''
    """for i in range(4, int(num ** 0.5) + 1):
        if num % i == 0:
            return i"""
    return ret

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("USAGE: factors <file>")
        sys.exit(1)
    file = open(sys.argv[1])
    for line in file:
        if line:
            num = int(line.strip())
        factor = find_factor(num)
        if factor:
            print("{:d}={:d}*{:d}".format(num, num // factor, factor))
