#!/usr/bin/python3
import sys

def find_factor(num):
    if num <= 3:
        return num
    elif num % 2 == 0:
        return 2
    elif num % 3 == 0:
        return 3

    for i in range(4, int(num ** 0.5) + 1):
        if num % i == 0:
            return i
    return None

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("USAGE: factors <file>")
        sys.exit(1)
    file = open(sys.argv[1])
    for line in file:
        if line:
            num = int(line.strip())
        factor = find_factor(num)
        if factor:
            print("{:d}={:d}*{:d}".format(num, num // factor, factor))
