#!/usr/bin/python3
import sys

def find_factor(num):
    for i in range(2, num + 1):
        if num % i == 0:
            return i
    return None

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("USAGE: factors <file>")
        sys.exit(1)
    file = open(sys.argv[1])
    for line in file:
        if line:
            num = int(line.strip())
        factor = find_factor(num)
        if factor:
            print("{:d}={:d}*{:d}".format(num, num // factor, factor))
