#!/usr/bin/python3
import sys, random
from math import gcd

def power(a, d, num):
    result = 1
    while d > 0:
        if d % 2 == 1:
            result = (result * a) % num
        a = (a ** 2) % num
        d //= 2
    return result

def isprime(num):
    if num <= 1 or num == 4:
        return False
    elif num <= 3:
        return True
    r = 0
    d = num - 1
    while d % 2 == 0:
        r += 1
        d //= 2
    for i in range(15):
        a = random.randint(2, num - 2)
        ret = power(a, d, num)
        if ret == 1 or ret == num - 1:
            continue
        for j in range(r - 1):
            ret = (ret ** 2) % num
            if ret == num - 1:
                break
            return False
    return True

def is_square(n):
    if n < 1:
        return False
    else:
        for i in range(int(n // 2) + 1):
            if (i * i) == n:
                return True
    return False

def find_factor(num):
    """
    for a in range(int((num ** 0.5) + 1), num):
        b = (a * a) - num
        if not is_square(b):
            continue
        b = int(b ** 0.5)
        p = a + b
        q = a - b
        if isprime(q) and isprime(p) and p * q == num:
            return p
    
    while True:
        x = y = random.randint(1, num - 1)
        c = random.randint(2, num - 1)
        f = lambda x: (x ** 2 + c) % num
        d = 1
        while d == 1:
            x = f(x)
            y = f(f(y))
            d = gcd(abs(x - y), num)
            if d != num and isprime(d):
                return d
    return d """
    x, y, d = 2, 2, 1
    f = lambda x: (x ** 2 + 1) % num
    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), num)
    return d

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("USAGE: factors <file>")
        sys.exit(1)
    file = open(sys.argv[1])
    for line in file:
        if line:
            num = int(line.strip())
        factor = find_factor(num)
        if factor:
            print("{:d}={:d}*{:d}".format(num, num // factor, factor))
    file.close()
